// Mocks generated by Mockito 5.4.4 from annotations
// in shuyuan_reader/test/presentation/controllers/book_detail_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:shuyuan_reader/data/services/download_service.dart' as _i2;
import 'package:shuyuan_reader/domain/entities/book.dart' as _i6;
import 'package:shuyuan_reader/domain/repositories/book_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i2.DownloadService {
  @override
  _i3.Future<String> downloadBook({
    required String? bookId,
    required String? url,
    required dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadBook,
          [],
          {
            #bookId: bookId,
            #url: url,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #downloadBook,
            [],
            {
              #bookId: bookId,
              #url: url,
              #onProgress: onProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #downloadBook,
            [],
            {
              #bookId: bookId,
              #url: url,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  void cancelDownload(String? bookId) => super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [bookId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> deleteBook(String? localPath) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [localPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i5.BookRepository {
  @override
  _i3.Future<List<_i6.Book>> getBooks({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i3.Future<List<_i6.Book>>.value(<_i6.Book>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Book>>.value(<_i6.Book>[]),
      ) as _i3.Future<List<_i6.Book>>);

  @override
  _i3.Future<_i6.Book?> getBookById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i3.Future<_i6.Book?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.Book?>.value(),
      ) as _i3.Future<_i6.Book?>);

  @override
  _i3.Future<void> saveBooks(List<_i6.Book>? books) => (super.noSuchMethod(
        Invocation.method(
          #saveBooks,
          [books],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateBook(_i6.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> shouldRefresh() => (super.noSuchMethod(
        Invocation.method(
          #shouldRefresh,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
