// Mocks generated by Mockito 5.4.4 from annotations
// in shuyuan_reader/test/presentation/pages/book_list/book_list_golden_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shuyuan_reader/domain/entities/book.dart' as _i4;
import 'package:shuyuan_reader/domain/usecases/get_book_by_id_usecase.dart'
    as _i6;
import 'package:shuyuan_reader/domain/usecases/get_books_usecase.dart' as _i2;
import 'package:shuyuan_reader/domain/usecases/refresh_books_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetBooksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBooksUseCase extends _i1.Mock implements _i2.GetBooksUseCase {
  MockGetBooksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> call({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);
}

/// A class which mocks [RefreshBooksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshBooksUseCase extends _i1.Mock
    implements _i5.RefreshBooksUseCase {
  MockRefreshBooksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);
}

/// A class which mocks [GetBookByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBookByIdUseCase extends _i1.Mock
    implements _i6.GetBookByIdUseCase {
  MockGetBookByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Book?> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<_i4.Book?>.value(),
      ) as _i3.Future<_i4.Book?>);
}
