// Mocks generated by Mockito 5.4.4 from annotations
// in shuyuan_reader/test/data/repositories/book_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shuyuan_reader/data/datasources/book_local_datasource.dart'
    as _i5;
import 'package:shuyuan_reader/data/datasources/book_remote_datasource.dart'
    as _i2;
import 'package:shuyuan_reader/data/models/book_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRemoteDataSource extends _i1.Mock
    implements _i2.BookRemoteDataSource {
  @override
  _i3.Future<List<_i4.BookModel>> fetchBooks() => (super.noSuchMethod(
        Invocation.method(
          #fetchBooks,
          [],
        ),
        returnValue: _i3.Future<List<_i4.BookModel>>.value(<_i4.BookModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.BookModel>>.value(<_i4.BookModel>[]),
      ) as _i3.Future<List<_i4.BookModel>>);
}

/// A class which mocks [BookLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookLocalDataSource extends _i1.Mock
    implements _i5.BookLocalDataSource {
  @override
  _i3.Future<List<_i4.BookModel>> getCachedBooks() => (super.noSuchMethod(
        Invocation.method(
          #getCachedBooks,
          [],
        ),
        returnValue: _i3.Future<List<_i4.BookModel>>.value(<_i4.BookModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.BookModel>>.value(<_i4.BookModel>[]),
      ) as _i3.Future<List<_i4.BookModel>>);

  @override
  _i3.Future<void> cacheBooks(List<_i4.BookModel>? books) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheBooks,
          [books],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastUpdateTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdateTime,
          [],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
        returnValueForMissingStub: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> setLastUpdateTime(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setLastUpdateTime,
          [time],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
