// Mocks generated by Mockito 5.4.4 from annotations
// in shuyuan_reader/test/presentation/controllers/reader/reader_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shuyuan_reader/data/datasources/reader/reading_local_data_source.dart'
    as _i12;
import 'package:shuyuan_reader/domain/entities/book.dart' as _i6;
import 'package:shuyuan_reader/domain/entities/reader/reader_settings.dart'
    as _i3;
import 'package:shuyuan_reader/domain/entities/reader/reading_progress.dart'
    as _i8;
import 'package:shuyuan_reader/domain/repositories/book_repository.dart' as _i4;
import 'package:shuyuan_reader/domain/repositories/reading_repository.dart'
    as _i2;
import 'package:shuyuan_reader/domain/usecases/reader/get_reading_progress.dart'
    as _i7;
import 'package:shuyuan_reader/domain/usecases/reader/save_reading_progress.dart'
    as _i9;
import 'package:shuyuan_reader/domain/usecases/reader/toggle_bookmark.dart'
    as _i10;
import 'package:shuyuan_reader/domain/usecases/reader/update_reader_settings.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReadingRepository_0 extends _i1.SmartFake
    implements _i2.ReadingRepository {
  _FakeReadingRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReaderSettings_1 extends _i1.SmartFake
    implements _i3.ReaderSettings {
  _FakeReaderSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i4.BookRepository {
  @override
  _i5.Future<List<_i6.Book>> getBooks({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<List<_i6.Book>>.value(<_i6.Book>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.Book>>.value(<_i6.Book>[]),
      ) as _i5.Future<List<_i6.Book>>);

  @override
  _i5.Future<_i6.Book?> getBookById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Book?>.value(),
        returnValueForMissingStub: _i5.Future<_i6.Book?>.value(),
      ) as _i5.Future<_i6.Book?>);

  @override
  _i5.Future<void> saveBooks(List<_i6.Book>? books) => (super.noSuchMethod(
        Invocation.method(
          #saveBooks,
          [books],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateBook(_i6.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> shouldRefresh() => (super.noSuchMethod(
        Invocation.method(
          #shouldRefresh,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [GetReadingProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReadingProgress extends _i1.Mock
    implements _i7.GetReadingProgress {
  @override
  _i2.ReadingRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ReadingRepository);

  @override
  _i5.Future<_i8.ReadingProgress?> call(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [bookId],
        ),
        returnValue: _i5.Future<_i8.ReadingProgress?>.value(),
        returnValueForMissingStub: _i5.Future<_i8.ReadingProgress?>.value(),
      ) as _i5.Future<_i8.ReadingProgress?>);
}

/// A class which mocks [SaveReadingProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveReadingProgress extends _i1.Mock
    implements _i9.SaveReadingProgress {
  @override
  _i2.ReadingRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ReadingRepository);

  @override
  _i5.Future<void> call(_i8.ReadingProgress? progress) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [progress],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ToggleBookmark].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleBookmark extends _i1.Mock implements _i10.ToggleBookmark {
  @override
  _i2.ReadingRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeReadingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ReadingRepository);

  @override
  _i5.Future<void> call({
    required String? bookId,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #bookId: bookId,
            #page: page,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UpdateReaderSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReaderSettings extends _i1.Mock
    implements _i11.UpdateReaderSettings {
  @override
  _i5.Future<void> saveDefault(_i3.ReaderSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDefault,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveForBook(
    String? bookId,
    _i3.ReaderSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveForBook,
          [
            bookId,
            settings,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> call(_i3.ReaderSettings? settings) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ReadingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingLocalDataSource extends _i1.Mock
    implements _i12.ReadingLocalDataSource {
  @override
  _i5.Future<void> saveDefaultSettings(_i3.ReaderSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDefaultSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveBookSettings(
    String? bookId,
    _i3.ReaderSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBookSettings,
          [
            bookId,
            settings,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.ReaderSettings getDefaultSettings() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultSettings,
          [],
        ),
        returnValue: _FakeReaderSettings_1(
          this,
          Invocation.method(
            #getDefaultSettings,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeReaderSettings_1(
          this,
          Invocation.method(
            #getDefaultSettings,
            [],
          ),
        ),
      ) as _i3.ReaderSettings);

  @override
  _i3.ReaderSettings getBookSettings(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #getBookSettings,
          [bookId],
        ),
        returnValue: _FakeReaderSettings_1(
          this,
          Invocation.method(
            #getBookSettings,
            [bookId],
          ),
        ),
        returnValueForMissingStub: _FakeReaderSettings_1(
          this,
          Invocation.method(
            #getBookSettings,
            [bookId],
          ),
        ),
      ) as _i3.ReaderSettings);

  @override
  _i5.Future<void> deleteBookSettings(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookSettings,
          [bookId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetDefaultSettings() => (super.noSuchMethod(
        Invocation.method(
          #resetDefaultSettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool hasBookSettings(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #hasBookSettings,
          [bookId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hasDefaultSettings() => (super.noSuchMethod(
        Invocation.method(
          #hasDefaultSettings,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
